

server.port=8010

spring.mongodb.uri=mongodb+srv://ak04238_db_user:TjKjHTXleFX8ztio@cluster0.pzfq9mh.mongodb.net/journal-db?appName=Cluster0

spring.data.mongodb.auto-index-creation=true

logging.level.org.springframework.data.mongodb=DEBUG